# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 810000a1389bcd0a346911176f24797982bd21c6ce7fa3bf5b982919a71a17f8ee803a90b46e65b7d64fd76c6e86fca1302ce9693e4b84ac7f215f8f6f233ca3

test:
  secret_key_base: 239dcaeef5e653aa347dea32bfb936f6a3e54f8d93c0af627a22c8c6c84093ded36ece402ec255a8514a8a8218db941928bd9db0a12fe988e8ac067496484c7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
